### ISSUE TITLE
Skeleton Texture

### ISSUE THREAD

**Issue by RhettWimmer** [WeirdistBuilds/Brodinjer#412]
![derfh.PNG](https://app.gitkraken.com/api/glo/boards/5f460e143d9b050011b79b97/attachments/5f76b10e0d832b001118305b)

![temp11.PNG](https://app.gitkraken.com/api/glo/boards/5f460e143d9b050011b79b97/attachments/5f7fc6dd0d832b00111a8bb2)

**Comment by dexspresso** [comment]
The bone texture is very nice. Let's tone down the white glow of their eyes just a tad so a halo can be placed in each one in Unity to really sell the glow effect.
